# Numpy Revision 

In [1]:
import numpy as np

In [4]:
nd1 = np.array([1,2,3])
print(nd1)
print(nd1.ndim)

[1 2 3]
1


In [5]:
nd2 = np.array([ [1,2,3], [4,5,6]])
print(nd2)
print(nd2.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
nd3 = np.array([ [ [1,2,3], [4,5,6]], [[7,8,9] , [1,2,3] ] ])
print(nd3)
print(nd3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
3


In [16]:
nd3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
nd3[1]

array([[7, 8, 9],
       [1, 2, 3]])

In [36]:
nd3 = np.array([ [ [1,2,3], [4,5,6]], [[7,8,9] , [1,2,3] ] ])
print(nd3)
print(nd3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
3


In [19]:
nd3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [20]:
nd3[1]

IndexError: index 1 is out of bounds for axis 0 with size 1

In [21]:
nd3.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [37]:
nd3.shape

(2, 2, 3)

In [32]:
np.array(3).shape

()

In [38]:
nd3.ndim

3

In [45]:
narr_tup = np.array( ((1,2,3,4),(5,6,7,8)) )

In [46]:
narr_tup

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
narr_tup.ndim

2

In [53]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
np.arange(1,11).shape

(10,)

In [57]:
np.arange(1,11).ndim

1

In [58]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [59]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
np.arange(1,11).reshape(2,5).ndim

2

In [61]:
np.arange(1,11).reshape(2,1,5)

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]]])

In [62]:
np.arange(1,11).reshape(2,1,5).ndim

3

In [63]:
np.arange(1,11).reshape(2,5,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [64]:
np.arange(1,11).reshape(2,5,1).ndim

3

In [65]:
np.arange(1,11).reshape(2,5,1,1)

array([[[[ 1]],

        [[ 2]],

        [[ 3]],

        [[ 4]],

        [[ 5]]],


       [[[ 6]],

        [[ 7]],

        [[ 8]],

        [[ 9]],

        [[10]]]])

In [67]:
np.arange(1,11).reshape(2,5,1,1).ndim

4

In [68]:
np.arange(1,11).reshape(2,5,1,1,1).ndim

5

In [69]:
np.arange(1,11).reshape(2,5,1,1,1)

array([[[[[ 1]]],


        [[[ 2]]],


        [[[ 3]]],


        [[[ 4]]],


        [[[ 5]]]],



       [[[[ 6]]],


        [[[ 7]]],


        [[[ 8]]],


        [[[ 9]]],


        [[[10]]]]])

In [70]:
np.arange(1,501)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [71]:
np.arange(1,55)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54])

In [72]:
np.arange(1,55).reshape(9,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [73]:
np.arange(1,55).reshape(3,3,6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18]],

       [[19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]],

       [[37, 38, 39, 40, 41, 42],
        [43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54]]])

In [74]:
np.arange(1,55).reshape(3,3,2,3)

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]]],


       [[[19, 20, 21],
         [22, 23, 24]],

        [[25, 26, 27],
         [28, 29, 30]],

        [[31, 32, 33],
         [34, 35, 36]]],


       [[[37, 38, 39],
         [40, 41, 42]],

        [[43, 44, 45],
         [46, 47, 48]],

        [[49, 50, 51],
         [52, 53, 54]]]])

In [75]:
np.arange(1,55).reshape(3,3,2,3).ndim

4

In [78]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
np.zeros((4,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [86]:
np.ones((5,)).ndim

1

In [88]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [93]:
np.identity(5,int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [94]:
np.identity(5,int).dtype

dtype('int64')

In [97]:
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [110]:
np.eye(6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [3]:

np.random.randint(1,100,size=6)

array([ 9, 51, 22, 74, 87, 84], dtype=int32)

In [16]:
np.random.randint(4,100,size=(2,2,2,2,2),dtype=np.int8)

array([[[[[40, 36],
          [44, 28]],

         [[74, 33],
          [37, 50]]],


        [[[ 4,  5],
          [41, 15]],

         [[21, 73],
          [57, 63]]]],



       [[[[55, 95],
          [96,  4]],

         [[20, 61],
          [23, 57]]],


        [[[60,  4],
          [79, 49]],

         [[45, 88],
          [27, 36]]]]], dtype=int8)

In [17]:
np.random.randint(4,100,size=(2,2,2,2,2),dtype=np.int8).ndim

5

In [19]:
np.random.randint(4,100,size=(2,2,2,2,2),dtype=np.int8).size

32

In [23]:
np.linspace(0,10,num=8)

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        ])

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
np.eye(4,5,6)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
a1 = np.arange(1,10)

In [34]:
a2 = np.arange(0,12).reshape(3,4)

In [35]:
a3 = np.arange(0,8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
np.max(a3) , np.min(a3)

(np.int64(7), np.int64(0))

In [39]:
np.max(a2),np.min(a2)

(np.int64(11), np.int64(0))

In [40]:
a2 * 3

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [42]:
np.prod(a2) # vecause a2 has 0 totla elements are multiplied

np.int64(0)

In [43]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
np.prod(a2[1,0:2])

np.int64(20)

In [46]:
for i in a3:
    print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [47]:
np.ravel(a3)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
for  i in np.ravel(a3):
    print(i)

0
1
2
3
4
5
6
7


In [49]:
l3 = [[[1,2,3], [1,2,3], [1,2,3]],[[1,2,3], [1,2,3], [1,2,3]],[[1,2,3], [1,2,3], [1,2,3]]]

In [50]:
for i in np.ravel(l3):
    print(i)

1
2
3
1
2
3
1
2
3
1
2
3
1
2
3
1
2
3
1
2
3
1
2
3
1
2
3


In [51]:
np.nditer(l3)

In [53]:
np.ravel(l3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3])

In [57]:
for i in np.nditer(l3):
    print(i)

(array(1), array(1), array(1))
(array(2), array(2), array(2))
(array(3), array(3), array(3))
(array(1), array(1), array(1))
(array(2), array(2), array(2))
(array(3), array(3), array(3))
(array(1), array(1), array(1))
(array(2), array(2), array(2))
(array(3), array(3), array(3))


In [56]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# Dot Product

In [5]:
a1 = np.arange(1,7).reshape(2,3)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a2 = np.arange(7,13).reshape(3,2)
a2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [7]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])

In [8]:
a2 = a2.reshape(1,6)
a2

array([[ 7,  8,  9, 10, 11, 12]])

In [10]:
np.dot(a1,a2)

ValueError: shapes (2,3) and (1,6) not aligned: 3 (dim 1) != 1 (dim 0)

# Numpy multipllication operation

In [15]:
a3 = np.arange(1,7).reshape(2,3)
a4 = np.arange(11,17).reshape(2,3)
print(a3)
print("************")
print(a4)

[[1 2 3]
 [4 5 6]]
************
[[11 12 13]
 [14 15 16]]


In [12]:
a3 + a4

array([[12, 14, 16],
       [18, 20, 22]])

In [16]:
a3 - a4

array([[-10, -10, -10],
       [-10, -10, -10]])

In [17]:
a3 * a4

array([[11, 24, 39],
       [56, 75, 96]])

# Broadcasting

In [19]:
a5 = np.arange(1,10).reshape(3,3)
a5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a6 = np.arange(1,4).reshape(3,1)
a6

array([[1],
       [2],
       [3]])

In [26]:
a7 = np.arange(1,9).reshape(2,4)
a7

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
a8 = np.arange(1,5).reshape(2,2)
a8

array([[1, 2],
       [3, 4]])

In [29]:
a7 * a8

ValueError: operands could not be broadcast together with shapes (2,4) (2,2) 