In [1]:
# NumPy Assignment

In [1]:
import numpy as np

In [9]:
# 1. Create a 1D Numpy array with values from 0 to 9.

In [3]:
my1darray = np.arange(0,10)
print(my1darray.ndim)

1


In [17]:
# 3. Create a Numpy array with values ranging from 10 to 49.

In [21]:
my1darray = np.array(np.arange(10,50))
print(my1darray)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [23]:
# 4. Create a 2D Numpy array and change the data type to float.

In [29]:
my2darray = np.arange(1,5, dtype=float).reshape(2,2)
print(my2darray)
print("Dimension is",my2darray.ndim)

[[1. 2.]
 [3. 4.]]
Dimension is 2


In [31]:
# 5. Create a 4x4 identity matrix.

In [39]:
my4identity = np.identity(4)
print("4X4 identity matrix is ", my4identity,sep="\n")

4X4 identity matrix is 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [43]:
# 6. Create a Numpy array with 10 values evenly spaced between 1 and 5.
mylinspace = np.linspace(1,5,10)
print(mylinspace)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [45]:
# 7. Create a 3x3 Numpy array with random values.

In [55]:
myrand = np.random.random(size=9).reshape(3,3)
print(myrand)

[[0.30523243 0.08382434 0.95251961]
 [0.68640365 0.22700558 0.69736724]
 [0.06680595 0.80093891 0.27625953]]


In [57]:
# 8. Create a Numpy array with 20 random values and reshape it to a 4x5 array.

In [59]:
myrand1 = np.random.random(size=20).reshape(4,5)
print(myrand1)

[[0.90105847 0.8329016  0.43508026 0.58971537 0.40166966]
 [0.31312369 0.4324101  0.64790497 0.32735402 0.59796829]
 [0.87664035 0.19310911 0.13838942 0.71931103 0.80192156]
 [0.218671   0.41337373 0.38399818 0.97156389 0.35950275]]


In [61]:
# 9. Create an array of shape (3, 3) and extract the values of the second row.

In [69]:
mysecondrow = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
print("Full array",mysecondrow,sep="\n")
print("the second row values are ",mysecondrow[1],sep="\n")

Full array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
the second row values are 
[4 5 6]


In [71]:
# 10. Create a 5x5 matrix with values 1 to 25 and extract the element in the third row and fourth column.

In [81]:
my5matrix = np.arange(1,26).reshape(5,5)
print("Original array is ",my5matrix,sep="\n")
print("3rd row and 4th column value is ",my5matrix[2,3],sep="\n")

Original array is 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
3rd row and 4th column value is 
14


In [83]:
# 11. Find the shape, size, and data type of a given Numpy array.

In [87]:
print("array is ",my2darray,sep="\n")
print("shape is ",my2darray.shape,sep="\n")
print("size is ",my2darray.size,sep="\n")
print("dtype is ",my2darray.dtype,sep="\n")

array is 
[[1. 2.]
 [3. 4.]]
shape is 
(2, 2)
size is 
4
dtype is 
float64


In [89]:
# 12. Flatten a given 2D Numpy array.

In [109]:
print("array is ",my2darray,sep="\n")
print("Flatten 2 d array is ",my2darray.reshape(1,4),sep="\n")
#or
print("Anothr method of Flatten 2 d array is ",my2darray.flatten(),sep="\n")

array is 
[[1. 2.]
 [3. 4.]]
Flatten 2 d array is 
[[1. 2. 3. 4.]]
Anothr method of Flatten 2 d array is 
[1. 2. 3. 4.]


In [95]:
# 13. Concatenate two Numpy arrays along the second axis.

In [103]:
np.concatenate((my2darray,my2darray),axis=1)

array([[1., 2., 1., 2.],
       [3., 4., 3., 4.]])

In [111]:
#14. Split a given Numpy array into 3 equal-sized sub-arrays.

In [131]:
my9array = np.arange(1,28).reshape(9,3)
print("Original array",my9array,sep="\n")

Original array
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]


In [133]:
mysplit,mysplit1,mysplit2 = np.split(my9array,3)
print("My first split",mysplit,sep="\n")
print("My second split",mysplit1,sep="\n")
print("My last split",mysplit2,sep="\n")

My first split
[[1 2 3]
 [4 5 6]
 [7 8 9]]
My second split
[[10 11 12]
 [13 14 15]
 [16 17 18]]
My last split
[[19 20 21]
 [22 23 24]
 [25 26 27]]


In [135]:
#15. Create a Numpy array with 10 random integers between 1 and 100, and find the maximum and minimum values.


In [141]:
np.random.random(100)*100

array([53.28703069, 53.01081056, 74.32561813, 69.27437022, 29.82357393,
       47.24840605, 21.91419294, 66.73668144, 15.05709878, 91.28095498,
       36.85051403, 61.93586634, 12.58277393,  8.54005569, 89.2196109 ,
       37.32122121, 33.4744667 ,  2.55845783, 74.25023574, 19.85919127,
       74.24411044, 26.77534486, 14.22328806, 38.47880964, 88.99311493,
       43.52645425, 88.37772686, 86.91584678, 45.47588984, 82.34658068,
        8.81370445, 87.09598592,  9.23722478, 14.51493946,  5.44954756,
       67.49121762, 23.70700773, 82.28388742, 74.37182128, 51.56283688,
       81.41763337, 92.91428103, 22.08987061, 72.7011443 , 11.07119237,
       25.98549228, 52.85483283, 10.95052204, 64.11335393,  0.76996967,
        8.62214625, 97.16100008, 69.27028935, 54.58044462,  4.30282998,
       55.80051792, 87.3375476 , 79.89734455,  8.17918374, 73.60679814,
       59.11584595, 25.2811028 , 21.15751248, 20.66118367, 65.23551629,
       92.25671189, 85.52394418, 45.26428243, 82.65987212, 18.85

In [151]:
print("Maximum numer from array is ",np.max(np.random.random(100)*100),sep="\n")
print("Minimum numer from array is ",np.min(np.random.random(100)*100),sep="\n")

Maximum numer from array is 
97.75405824558588
Minimum numer from array is 
2.5469462686773636


In [153]:
#16. Create a Numpy array with random values and replace all values greater than 0.5 with 1.


In [181]:
myarray = np.random.random(10).reshape(5,2)
print("Original array is ",myarray,sep="\n")
myarray[myarray>.5] = 1
print("Array replaces with 1",myarray,sep="\n")

Original array is 
[[0.60310809 0.10773725]
 [0.75847333 0.05126247]
 [0.52801734 0.71466936]
 [0.64385785 0.63006216]
 [0.89461262 0.36329718]]
Array replaces with 1
[[1.         0.10773725]
 [1.         0.05126247]
 [1.         1.        ]
 [1.         1.        ]
 [1.         0.36329718]]


In [183]:
#17. Multiply two given Numpy arrays element-wise.

In [185]:
print(mysplit)
print(mysplit1)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [187]:
print(mysplit * mysplit1)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [217]:
# another method
np.multiply(mysplit,mysplit1)

array([[ 10,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [189]:
# 18. Compute the dot product of two given Numpy arrays.

In [201]:
np.array([1,2,3,4])


array([[1],
       [2],
       [3],
       [4]])

In [203]:
np.array([1,2,3,4]).reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [233]:
# another method
np.dot(np.array([1,2,3,4]),np.array([1,2,3,4]).reshape(4,1))

array([30])

In [207]:
# 19. Add a scalar value to a given Numpy array.

In [239]:
print("Original array is ",mysplit,sep="\n")
print("Adding scalar 5 to it",mysplit + 5,sep="\n")

Original array is 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Adding scalar 5 to it
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [209]:
#20. Subtract one Numpy array from another.

In [237]:
print(mysplit)
print(mysplit1)
print("Subtracted array is ",mysplit1 - mysplit,sep="\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Subtracted array is 
[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [2]:
# 21. Find the mean, median, and standard deviation of a given Numpy array.

In [8]:
print("Mean is ",np.mean(my1darray))
print("Meadian is ",np.median(my1darray))
print("Standard Deviation is ",np.std(my1darray))

Mean is  4.5
Meadian is  4.5
Standard Deviation is  2.8722813232690143


In [5]:
my1darray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.sum(my1darray)

np.int64(45)

In [10]:
#22. Sort a given Numpy array along the first axis.

In [14]:
myrandom_mat = np.random.random(9).reshape(3,3)
myrandom_mat

array([[0.17383467, 0.50734516, 0.35506127],
       [0.83402801, 0.8583105 , 0.42536646],
       [0.27413606, 0.64255899, 0.25066982]])

In [17]:
np.sort(myrandom_mat,axis=0)

array([[0.17383467, 0.50734516, 0.25066982],
       [0.27413606, 0.64255899, 0.35506127],
       [0.83402801, 0.8583105 , 0.42536646]])

In [19]:
# 23. Find the unique elements of a given Numpy array.
np.array([1,2,3,1,2,3,4,5,5,6,6,7,7])
np.unique(np.array([1,2,3,1,2,3,4,5,5,6,6,7,7]))

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
# 24. Check if a given Numpy array contains any NaN values.


In [22]:
myarray = np.random.random(10).reshape(5,2)
myarray

array([[0.08645042, 0.64537145],
       [0.23427316, 0.29400096],
       [0.17528515, 0.51418565],
       [0.39404879, 0.10422382],
       [0.26968589, 0.23793529]])

In [23]:
myarray[myarray > .30] = np.nan
myarray

array([[0.08645042,        nan],
       [0.23427316, 0.29400096],
       [0.17528515,        nan],
       [       nan, 0.10422382],
       [0.26968589, 0.23793529]])

In [26]:
np.isnan(myarray).any()

np.True_

In [27]:
# 25. Create a 5x5 matrix and pad it with zeros along the border.

In [28]:
np.pad(np.arange(1,26).reshape(5,5),pad_width=1,constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  0],
       [ 0,  6,  7,  8,  9, 10,  0],
       [ 0, 11, 12, 13, 14, 15,  0],
       [ 0, 16, 17, 18, 19, 20,  0],
       [ 0, 21, 22, 23, 24, 25,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [29]:
# 26. Transpose a given Numpy array.

In [36]:
print("Before Transpose",myarray,sep='\n')
print("After transpose ",myarray.T,sep='\n')

Before Transpose
[[0.08645042        nan]
 [0.23427316 0.29400096]
 [0.17528515        nan]
 [       nan 0.10422382]
 [0.26968589 0.23793529]]
After transpose 
[[0.08645042 0.23427316 0.17528515        nan 0.26968589]
 [       nan 0.29400096        nan 0.10422382 0.23793529]]


In [37]:
# 27. Reverse the rows of a given 2D Numpy array.

In [43]:
print("Before reversal", myarray,sep='\n')
myarray[:,::-1]

Before reversal
[[0.08645042        nan]
 [0.23427316 0.29400096]
 [0.17528515        nan]
 [       nan 0.10422382]
 [0.26968589 0.23793529]]


array([[       nan, 0.08645042],
       [0.29400096, 0.23427316],
       [       nan, 0.17528515],
       [0.10422382,        nan],
       [0.23793529, 0.26968589]])

In [58]:
# 28. Compute the cumulative sum of a given Numpy array.
mytest = np.arange(1,10).reshape(3,3)
print(mytest)
print("Cumulative sum of entire array")
print(np.cumsum(mytest))
print("Cumulative sum of along row array")
print(np.cumsum(mytest,axis=1))
print("Cumulative sum of along columns array")
print(np.cumsum(mytest,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Cumulative sum of entire array
[ 1  3  6 10 15 21 28 36 45]
Cumulative sum of along row array
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]
Cumulative sum of along columns array
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [62]:
# 29. Normalize a given Numpy array.
print(mytest)

normalized = (mytest - np.min(mytest)) / ( np.max(mytest) - np.min(mytest)) 
print("normalized array is",normalized)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
normalized array is [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]


In [46]:
# 30. Reshape a given Numpy array to have 1 row and multiple columns.

In [50]:
mytest = np.arange(1,10).reshape(3,3)
mytest

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
mytest.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [53]:
mytest.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])