# Numpy Practice

In [2]:
import numpy as np

In [3]:
### 1. Write a  NumPy program to print the NumPy version on your system.

In [5]:
print(np.__version__)

1.24.3


In [12]:
mylist = [12.23, 13.32, 100, 36.32]
myarr = np.array(mylist,dtype=float)
print("Original list is ",mylist)
print("One-dimensional NumPy array:",myarr)

Original list is  [12.23, 13.32, 100, 36.32]
One-dimensional NumPy array: [ 12.23  13.32 100.    36.32]


In [28]:
myarr = np.arange(2,11,dtype=int).reshape(3,3)
print("Created matrix is",myarr,sep='\n')

Created matrix is
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [24]:
myarr = np.zeros(10)
print("array generated ",myarr,sep="\n")
myarr[6] = 11
print("after 6th position updated",myarr, sep="\n")

array generated 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
after 6th position updated
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [30]:
myarr = np.arange(12,38)
print("Generated array is ",myarr)

Generated array is  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [32]:
myarr = np.arange(12,38)
print("Original array is ",myarr,sep="\n")
myarr1= myarr[::-1]
print("Reversed array is ",myarr1,sep="\n")

Original array is 
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reversed array is 
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [39]:
myarr = np.array([1,2,3,4])
print("Original array is ",myarr,sep="\n")

myfarr = np.asfarray(myarr) #asfarray means converting to floating point
print("Array converted to a float type:",myfarr,sep="\n")


Original array is 
[1 2 3 4]
Array converted to a float type:
[1. 2. 3. 4.]


In [55]:
x = np.ones((5, 5))
print("Original array",x,sep="\n")

Original array
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [17]:
x[1:4,1:4] = 0

In [18]:
print("1 on the border and 0 inside in the array",x,sep="\n")

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
y = np.zeros((5,5))
print("Original array:",y,sep="\n")

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
y[1:4,1:4] = 1
print("1 on the border and 0 inside in the array",y,sep="\n")

1 on the border and 0 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [61]:
# another method to append os inside array is :
z = np.ones((3,3))
z = np.pad(z,pad_width = 1,mode='constant',constant_values=0)

In [62]:
z

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [76]:
my8 = np.zeros((8,8))
my8[::2,1::2] = 1
my8[1::2, ::2] = 1
my8

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [80]:
mylist = [1,2,3,4,5,6,7,8]
print("List to array:",np.array(mylist),sep="\n")
mytuple = (8,4,6,1,2,3)
print("Tuple to array:",np.array(mytuple).reshape(2,3),sep="\n")

List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
 [1 2 3]]


In [88]:
org_arr = np.array([10,20,30])
print("Original array:",org_arr,sep="\n")
org_arr = np.append(org_arr,[40,50,60,70,80,90],axis=0)
print("After append values to the end of the array:",org_arr,sep="\n")

Original array:
[10 20 30]
After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]
