In [1]:
import numpy as np

In [7]:
a1 = np.arange(1,7).reshape(2,3)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a2 = np.arange(7,13).reshape(3,2)
a2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
np.dot(a1,a2)

array([[ 58,  64],
       [139, 154]])

In [2]:
a3 = np.arange(7,13).reshape(1,6)
a3

array([[ 7,  8,  9, 10, 11, 12]])

In [23]:
np.dot(a1,a3)

ValueError: shapes (2,3) and (1,6) not aligned: 3 (dim 1) != 1 (dim 0)

## Normal numpy array operation

In [62]:
a5 = np.arange(1,5).reshape(2,2)
a6 = np.arange(5,9).reshape(2,2)


In [64]:
print(a5)
print(a6)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [66]:

a5 + a6

array([[ 6,  8],
       [10, 12]])

In [38]:
a5 - a6

array([[-4, -4],
       [-4, -4]])

In [40]:
a5 * a6

array([[ 5, 12],
       [21, 32]])

In [42]:
a5 / a6

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [68]:
a7 = np.arange(1,11).reshape(5,2)

In [70]:
a7

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [72]:
a8 = np.arange(1,3).reshape(2,1)

In [74]:
a8

array([[1],
       [2]])

In [76]:
a7 + a8

ValueError: operands could not be broadcast together with shapes (5,2) (2,1) 

In [11]:
a9 = np.arange(1,17).reshape(4,4)
a9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
a10 = np.arange(1,5).reshape(1,4)
a10

array([[1, 2, 3, 4]])

In [17]:
a9 + a10

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16],
       [14, 16, 18, 20]])