In [1]:
import numpy as np # alias

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__git_version__',
 '__loader__',

In [7]:
n0 = np.array(3) # 0 d array
n0.ndim

0

In [8]:
n1 = np.array([1,2,3])

In [9]:
n1.ndim

1

In [12]:
n2 = np.array( [ [1,2,3],[4,5,6] ] )
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
n2.ndim

2

# we can create array with sequence / iterable or an array like object

specify the type or result array

In [14]:
np.array([1,2,3],dtype='str')

array(['1', '2', '3'], dtype='<U1')

In [15]:
np.array([1,2,3],dtype=int)

array([1, 2, 3])

In [16]:
np.array([1,2,3],dtype='int')

array([1, 2, 3])

In [19]:
np.array([1,2,3],dtype=np.int8)

array([1, 2, 3], dtype=int8)

In [21]:
np.array(['1',2,3],dtype=np.int32)

array([1, 2, 3])

In [22]:
np.array(['python',2,3],dtype=np.int16)

ValueError: invalid literal for int() with base 10: 'python'

In [23]:
# range

In [24]:
np.array(list(range(1,10)))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,-3)

array([], dtype=int32)

In [27]:
list(range(0,4,1.5))

TypeError: 'float' object cannot be interpreted as an integer

In [28]:
np.arange(0,4,1.5)

array([0. , 1.5, 3. ])

In [2]:
# shape & reshape

In [4]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [7]:
np.arange(1,10).shape

(9,)

In [8]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(1,10).reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [11]:
np.arange(1,10).reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
np.arange(1,10).reshape(2,3) # error beacuse 2*3 - 6 but we have 9 elements

ValueError: cannot reshape array of size 9 into shape (2,3)

In [15]:
np.arange(1,17).reshape(16,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [16]:
np.arange(1,17).reshape(1,16)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16]])

In [17]:
np.arange(1,17).reshape(8,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [18]:
np.arange(1,17).reshape(2,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [19]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [20]:
np.arange(1,17).reshape(2,4,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]])

In [21]:
np.arange(1,17).reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [25]:
np.arange(1,9).reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
np.arange(4,5).reshape(1,1,1,1,1,1,1,1,1,1,1).ndim

11

In [37]:
np.zeros((5,1),dtype=int)

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [39]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.identity((3,4))

TypeError: 'tuple' object cannot be interpreted as an integer

In [51]:
np.eye(4,5,1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
(np.random.random((5,5))).reshape(25,1)

array([[0.92190468],
       [0.3939531 ],
       [0.31732188],
       [0.40090134],
       [0.34703463],
       [0.81488177],
       [0.1859472 ],
       [0.35234649],
       [0.26108245],
       [0.03389483],
       [0.47703342],
       [0.63515322],
       [0.71208324],
       [0.9429356 ],
       [0.28325371],
       [0.37916464],
       [0.41827625],
       [0.5612609 ],
       [0.76551265],
       [0.91171775],
       [0.64616827],
       [0.93964387],
       [0.27141839],
       [0.35948543],
       [0.20354344]])

In [57]:
np.random.random((2,2,3))*100

array([[[20.36422178, 92.65308383, 77.9661938 ],
        [15.72692811, 13.26949305, 80.9889409 ]],

       [[ 7.50233506, 93.43865751, 85.36938194],
        [ 0.43784775, 97.07035461, 93.60295368]]])

In [65]:
np.random.randint(1,10,(4,16))

array([[4, 5, 9, 5, 4, 8, 7, 2, 1, 7, 6, 9, 9, 5, 9, 5],
       [5, 7, 2, 7, 5, 4, 8, 9, 6, 8, 4, 9, 6, 5, 5, 5],
       [4, 5, 6, 3, 6, 4, 9, 1, 6, 1, 1, 3, 9, 7, 1, 9],
       [4, 8, 7, 5, 5, 4, 7, 5, 2, 3, 5, 4, 8, 5, 8, 9]])

In [71]:
np.linspace(0,10,num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [82]:
np.linspace(1,9,4).reshape(1,4)

array([[1.        , 3.66666667, 6.33333333, 9.        ]])

# Array Attributes

In [ ]:
shape
ndim
size
itemsize
dtype
astype
where
ravel
nditer


In [88]:
a1 = np.arange(0,7,dtype=np.float32)

# Array operation

In [89]:
a1 = np.arange(1,10)

In [90]:
a1[0]

1

In [91]:
a1[0],a1[9]

IndexError: index 9 is out of bounds for axis 0 with size 9

In [104]:
a2 = np.arange(0,12).reshape(3,4)

In [105]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
a2[1]

array([4, 5, 6, 7])

In [97]:
type(a2)

numpy.ndarray

In [121]:
a2[2][2]

34

In [118]:
a2[2]

array([ 8,  9, 34, 11])

In [119]:
type(a2[2][2])

numpy.int32

In [114]:
a1 /10


array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [115]:
a1 + 5

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [122]:
a1 - 5

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [123]:
1 % 2

1

In [124]:
2 % 2

0

In [125]:
a1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a1 > 3

array([False, False, False,  True,  True,  True,  True,  True,  True])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [137]:
a3 = np.array([1,2,3],dtype=np.int32)

In [138]:
a3[0]

1

In [140]:
a3[0] = 34.56

In [141]:
a3

array([34,  2,  3])

In [142]:
a1 = np.arange(0,4).reshape(2,2)

In [143]:
a1

array([[0, 1],
       [2, 3]])

In [144]:
np.max(a1) # if no axis provided then complete 

3

In [ ]:
# axis is row or column 0 for column and 1 for row

In [145]:
np.max(a1,axis=1)

array([1, 3])

In [146]:
np.max(a1,axis=0)

array([2, 3])

In [148]:
np.min(a1,axis=0)

array([0, 1])

In [149]:
np.prod(a1)

0

In [152]:
np.prod(a1,axis=0)

array([0, 3])

In [153]:
np.mean(a1)

1.5

In [158]:
np.array(np.arange(1,10),dtype=int).reshape(3,3)[0:2]>2

array([[False, False,  True],
       [ True,  True,  True]])